# Generated by Django 3.2.18 on 2024-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_content', models.TextField()),
                ('voice_content', models.FileField(blank=True, null=True, upload_to='voice_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
