# Generated by Django 3.2.18 on 2024-03-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_by',
        ),
    ]
